---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install nvm,npm,node"
  become: yes
  become: true
  shell: |
    curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
    source ~/.profile
    nvm install --lts

- name: "install dependencies."
  become: yes
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes


- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present