---
- name: "unarchive backend files"
  unarchive:
    src: artifact.tar
    dest: /home/ubuntu/

- name: "executing node"
  shell: |
    cd /home/ubuntu/dist
    pm2 stop default
    pm2 start npm --name 'udapeople' -- start
    pm2 ls