---
- name: Creates App directory
  file:
    path: ~/app
    state: directory
    

- name: "unarchive backend files"
  unarchive:
    src: artifact.tar
    dest: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
    mode: 0755

  
- name: "executing node"
  shell: |
    cd /home/ubuntu/app/backend/dist
    pm2 stop default
    pm2 start npm --name 'udapeople' -- start
    pm2 ls